"""add_uuid_to_conversations

Revision ID: ee64db922283
Revises: b8d8f31e1201
Create Date: 2025-10-19 18:49:45.433491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee64db922283'
down_revision: Union[str, None] = 'b8d8f31e1201'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('uuid', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_conversations_uuid'), 'conversations', ['uuid'], unique=True)
    op.create_unique_constraint(None, 'conversations', ['id'])
    op.create_unique_constraint(None, 'messages', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='unique')
    op.drop_constraint(None, 'conversations', type_='unique')
    op.drop_index(op.f('ix_conversations_uuid'), table_name='conversations')
    op.drop_column('conversations', 'uuid')
    # ### end Alembic commands ###
